version: '3'

services: 
    app: 
      build: . 
      command: yarn dev
      ports:
        - '3000:3000'
      volumes: 
        - .:/app/
        - /app/node_modules
      env_file:
        - .env
    
    mongo:
      image: mongo
      restart: always
      ports:
        - '27017:27017'
      volumes:
        - ./mongo:/data/db

        