
name: Release new version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      url_user: ${{secrets.URL_USER}}
    steps:
      - uses: actions/checkout@v2
      
      - name: Collect sonar metrics
        run: curl "${{env.url_user}}" > fga-eps-mds-2021_1-MULTILIND_USER-$(date '+%Y-%m-%d-%H:%M').json

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          artifacts: fga-eps-mds-2021_1-MULTILIND_USER-$(date '+%Y-%m-%d-%H:%M').json
